spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://localhost:3306/covidtesting?serverTimezone=UTC
    username: root
    password: yyf1997213
  jpa:
    hibernate:
     ddl-auto: none
    properties:
     dialect: org.hibernate.dialect.MySQLDialect
     format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
