spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  datasource:
    url: jdbc:mysql://121.41.88.205:6240/codejavadb
    username: root
    password: root
  jpa:
    hibernate:
     ddl-auto: none
    properties:
     dialect: org.hibernate.dialect.MySQLDialect
     format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
